# Generated by Django 5.2.8 on 2026-01-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('FILE', 'File')], db_index=True, default='FILE', max_length=10),
        ),
    ]
